### PR TITLE
Add libnoise as submodule

### PR DESCRIPTION
**Pull request by hryniuk**
It's required to finish #62 and finally complete Travis configuration.

### CODE REVIEW

**Comment by serin-delaunay** [comment]
I think the submodule should be in the folder `lib/libnoise/`.

**Comment by hryniuk** [comment]
Yeah, I thought so too, but... **it will require changing all include directives and will have an impact on other PRs**. I'll do it, just a warning.

**Comment by serin-delaunay** [comment]
Why would it affect include directives? If `lib/libnoise/src/` is added as an include folder, the current `#include <noise/noise.h>` directives should work fine.

**Comment by hryniuk** [comment]
You're right, I don't know why I didn't notice it :frowning:.

**Comment by hryniuk** [comment]
Ok, now it should be alright. I've also changed `CMakeLists.txt` in #62 to include `libnoise` instead of `noise`.

**Comment by serin-delaunay** [comment]
Great :) I'll work on a PR to get the VS build using libnoise from the submodule.

**Comment by hryniuk** [comment]
Wow, nice :). In an ideal world compilation would be the same on all platforms. I'll check cmake builds with CLion on Windows in my spare time.

**Comment by serin-delaunay** [comment]
Once CI builds with CMake are working on https://appveyor.com or https://visualstudio.com (#20), I think it would be best to remove the VS stuff from the repository (I'll keep it for personal use). I'll start working on that once Travis builds are working. I've re-enabled Travis for Wangscape/Wangscape (transferring to the organisation had disabled it).

**Pull request merged**
